### ISSUE TITLE
More proper name for this project? clusterfile-spec, cluster-api, cluster-spec?

### ISSUE THREAD

**Issue by allencloud** [sealerio/api#1]
I am wondering if the project name api is too ambiguous. Actually the word `api` is too abstract and contains less information.

While we need to concept which must be more concrete than `api`. Maybe `clusterfile-spec`, `cluster-api`, `cluster-spec` ?

Just throw out my confusion, and wish to lead to warm discussion of this topic.

@sealerio/sealer-maintainers

**Comment by fanux** [comment]
cluster-spec +1

**Comment by allencloud** [comment]
OK, let's nail that down. cluster-spec.
